### ISSUE TITLE
Design pattern for supporting tables without primary keys

### ISSUE THREAD

**Issue by kazetsukaimiko** [ojplg/hrorm#1]
Hello there, I've been looking around for good, solid minimalist libraries to handle queries to Azure Datawarehouse (ADW). ADW is a bit of a weird animal, with a MS-SQL driver interface but more distributed and "NoSQL like" in implementation. Our use cases make unique keys of any kind (+ their indexes) impractical, not really useful, and a drain on performance.

Looking at your library, it would be fairly easy for me to add support for tables without a primary key in a fork, but long term it would be better to get any of these changes merged up to the origin. I'm wondering if there's any design pattern you'd entertain for merging into your codebase. Each project maintainer has their own vision for their projects, and I'd like to respect that.

As for approaches, my immediate instinct would be to subclass Dao and DaoBuilder, moving all singular row operations into the subclass (now named Dao and DaoBuilder themselves). The existing DaoBuilder/Dao classes (now superclasses) would probably get renamed to something like NonSignularDao{Builder}, omitting all non-singular operations in the Dao class. I think this way, existing behavior will not change significantly. To take advantage of this functionality, one would have to explicitly use the NonSingular variants.

I'm also curious about the design decision to enforce Long as the primary key type, as we use UUIDs quite alot. It certainly is the most common use case by far (Auto-increment PKs), but at a 30,000ft view it seems easy just to let it be generic. I ask because this might be useful as well to implement.

Thanks for your time and consideration.

**Comment by ojplg** [comment]
Hello.

Thanks for taking an interest in hrorm! I would be happy to work with you to try to make it useful for your use-case, but at the moment, I am afraid I do not understand it.

Hrorm depends on things having unique IDs for two things that seem pretty intrinsic to me.
* Selection. There are other ways to select things, but selecting by ID seems important.
* Joining. Hrorm supports relationships between objects, and depends on IDs for doing that. Without IDs, how will it support relations?

Living without selection by ID is of course possible for many things, but living without joining?

Perhaps I am totally misunderstanding what you are trying to do.

In terms of design ethos, hrorm generally tries to make the client interface easy, even at the expense of some implementation ugliness.

Here's what's important to hrorm, in my opinion. Hrorm clients should be able to write code like this:

` DaoBuilder<Item> itemDaoBuilder = new DaoBuilder<>().withStuff() .... ;`
` Dao<Item> itemDao = itemDaoBuilder.build(connection);`

And the itemDao should have the fullest power of select, insert, etc. All the operations supported.

When I added support for immutable object models via `IndirectDaoBuilder` I went through some trouble to preserve the code above. In fact, the implementation is quite clunky in order to make the client code simpler.

Perhaps a better solution (for hrorm even as it exists today) as well as for your ideas, is to introduce an `AbstractDaoBuilder<T,B>` that is a fully abstract class, and have all the various `DaoBuilder` implementation inherit from it, including your own proposed `NonSingularDaoBuilder`. And if a `NonSingularDaoBuilder` creates a data access object that does not support, for instance, select by ID, then it should create a `NonSingularDao` and `Dao` should subclass *that* by adding in the other select methods.

Again, I might be totally misunderstanding your proposal.

The design decision about `long` primary keys has more to do with keeping the database as the singular source of truth. Hrorm wants to work with database sequences, which naturally map to Java `long` values. If you really like UUIDs and want to issue those outside the database, that's a very reasonable approach for certain architectures. At the moment, hrorm is more database-centric, but if we can find a clean way to support it, I am not against allowing primary keys to be generated outside the database. We will need to decide between two approaches: passing a generator to a `DaoBuilder` or, just having that happen externally. It changes how `insert` works for clients if you do the second, so at first glance, I favor passing the generator to the `DaoBuilder`.

I hope this answers some of your questions and gives a better idea of why hrorm looks like it does.

If you're interested in pursuing this further, like I said, I am happy to work with you on it.

**Comment by kazetsukaimiko** [comment]
Thanks you for your response! That was quick.

I guess the use case I would want to support in this contribution would be one where one is doing large, aggregate operations on a distributed dataset, and the individual rows themselves don't really matter. There's no use case for individual selects.

The overhead of maintaining a primary key field at all is quite high for us due to the volume of data being inserted and the distributed nature of the datastore- you would have to synchronize that unique, incrementing field across all nodes and datacenters, which makes Sequence PKs prohibitive. By omitting these fields we avoid blocking operations as rows are inserted. 

So, addressing your questions: 
-Individual selection isn't important here.
-By extension somewhat, we're not joining on any other tables. The data doesn't have foreign relationships, its all atomic.

"In terms of design ethos, hrorm generally tries to make the client interface easy, even at the expense of some implementation ugliness."
I really love what you present as an interface. This is one of the attractions of this library for me- you went for standard CRUD without a ton of bells and whistles without one having to write SQL. Everything else was up to us- transactions et al. 

In my tests using your library, I'm actually passing your DAOs to a CPython script via JEP (https://github.com/ninia/jep)- and it is incredibly easy to use. Its simplicity lends itself well to scripting. (Python doesn't have an ORM that works with ADW- we're stuck with pyODBC and SQL)

"And the itemDao should have the fullest power of select, insert, etc. All the operations supported."
I would agree, and I think the use case I've presented and this sentiment aren't exclusive. I think a safe distinction can be made between inherently individualistic and inherently pluralistic data. For the pluralistic use case, we're just making less assumptions about the data itself, specifically around identifiers.

For example, if you're tracking Books in a number of Libraries, its useful to keep track of each Book, in each Library. But what if you wanted to track what portions of the Book were most read and when?  Would you really care about each time a sentence in the Book were read, enough to absolutely need to get an individual row representing that Event? Or would you care more about the aggregates, representing when the Book was popular and what parts of it were consumed the most, and with which audiences?

AbstractDaoBuilder<T,B>: Your suggestion sounds very, very similar to my own,
and AbstractDaoBuilder<T, B> itself sounds like a good idea to implement as well. But I guess where my idea differs, is that my proposed change is making DAOs with singular operations a superset of the existing DAOs, which will only contain plural operations.
```

public interface Dao<ENTITY> {
    long insert(ENTITY item);
    void update(ENTITY item);
    void delete(ENTITY item);
    ENTITY select(long id);
    List<ENTITY> selectMany(List<Long> ids);
    List<ENTITY> selectAll();
    ENTITY selectByColumns(ENTITY item, String... columnNames);
    List<ENTITY> selectManyByColumns(ENTITY item, String... columnNames);
    long atomicInsert(ENTITY item);
    void atomicUpdate(ENTITY item);
    void atomicDelete(ENTITY item);
    <T> T foldingSelect(ENTITY template, T identity, BiFunction<T,ENTITY,T> accumulator, String ... columnNames);
    Queries queries();
}

```

Would become:

```

public interface PluralDao<ENTITY> {
    Optional<Long> insert(ENTITY item); // No primary key = empty.
    List<ENTITY> selectAll();
    List<ENTITY> selectManyByColumns(ENTITY item, String... columnNames);
    Optional<Long> atomicInsert(ENTITY item); // No primary key = empty.
    
    Queries queries();

    <T> T foldingSelect(ENTITY template, T identity, BiFunction<T,ENTITY,T> accumulator, String ... columnNames);
}
public interface Dao<ENTITY> extends PluralDao<ENTITY> {
    void update(ENTITY item);
    void delete(ENTITY item);
    ENTITY select(long id);
    ENTITY selectFirstByColumns(ENTITY item, String... columnNames);
    List<ENTITY> selectMany(List<Long> ids);
    void atomicUpdate(ENTITY item);
    void atomicDelete(ENTITY item);
    
    Queries queries(); // Override to have superset of PluralDao's
}
```

This is without exploring it yet, I'll make a fork and see what this looks like. I really appreciate your response, lets save the primary key column type question for another branch/endeavor. I'd like to flesh this out to see if it will work.

**Comment by kazetsukaimiko** [comment]
I guess I'd also add something along the lines of these methods to PluralDao<ENTITY>:

```
    /**
     * Deletes multiple records from the database by some search criteria.
     *
     * @param item An instance of type ENTITY with populated values corresponding to the
     *             column names to select by.
     * @param columnNames The names of the database columns
     * 
     */
    List<ENTITY> deleteManyByColumns(ENTITY item, String... columnNames);
    
    /**
     * Update multiple records from the database by some search criteria.
     *
     * @param selectionItem An instance of type ENTITY with populated values corresponding to the
     *             column names to select by.
     * @param selectionColumnNames The names of the database columns to select by.
     *
     * @param updateItem An instance of type ENTITY with populated values corresponding to the
     *             column names to update to.
     * @param updateColumnNames The names of the database columns to update.
     */
    List<ENTITY> updateManyByColumns(ENTITY selectionItem, String[] selectionColumnNames, ENTITY updateItem, String[] updateColumnNames);
   
```

**Comment by ojplg** [comment]
It sounds like what you want is to be able to make queries against an entity that is represented in the database space by a single table and in the object space by a single class. Moreover this entity has no assigned primary key. Is that right?

As I mentioned above, one of the key capabilities of hrorm right now is that it supports relationships between entities, both in the database and in the object model.

So, to do what you want means building some things that are smaller and simpler than what hrorm supports now.

If I have this correct it seems like what you want is

* `KeylessAbstractDaoBuilder`
* `AbstractDaoBuilder extends KeylessAbstractDaoBuilder`
* `KeylessDaoBuilder extends KeylessAbstractDaoBuilder`
* `DaoBuilder extends AbstractDaoBuilder`

That means also changing how the `DaoDescriptor` interface works, since things that are "Keyless" cannot be used in join relationships in any way that hrorm can understand. Or maybe just that Keyless things do not implement `DaoDescriptor`, since they are only useful for building `Dao` objects, and not for relating to other entities.

I think I prefer the name "Keyless" to your suggestion of "Plural" since I think the plurality is something that *any* Dao could support. That's something that could be added to hrorm without the keylessness.

Am I understanding what you want correctly? Does my description make sense?

**Comment by kazetsukaimiko** [comment]
Your description is accurate. Our use case is simpler than the assumptions HRORM makes about table structures today.

Here's my efforts on this for the night:
https://github.com/ojplg/hrorm/compare/master...kazetsukaimiko:keyless

I really screwed up the git history, I'll fix that before I'll issue any PRs.

What's left to do functionally to test a Keyless table from what I can see would be to make a DAOBuilder for Keyless Daos, then change the Validator to throw up if there are any joins without PKs. There's much more (like the two additional methods I mentioned) than that, but just to get something to play with...

Architecturally, I'll do what I can to satisfy your preferences. Already some "Ugh" in there, like the new Assert.assertTrue(id.isPresent()) in tests... just trying to get those passing (they do, command line- my IntelliJ install can't seem to find some of the Lombok generated builder stuff). So far I don't think there's alot of actual behavior changes to be made, just moving stuff around for the most part. You know the code better than I do though, so...

For DaoDescriptor, I merely introduced Optional to try to get to something working. Its a good interface I think can be applied to this use case... Maybe I should just continue the pattern, get rid of Optional, add a KeylessDaoDescriptor in the same manner?

**Comment by ojplg** [comment]
Not sure what your intellij situation is, but there's a specific lombok plugin for intellij that works great for me.

I have not looked at your code yet, but thought I would mention that, since perhaps that will make your life easier.

**Comment by kazetsukaimiko** [comment]
I have the plugin installed and the annotation processor config. I'll look into it tomorrow, its not a big deal.

**Comment by kazetsukaimiko** [comment]
What finally fixed the IDE issues for me was bumping the Lombok version:
1.16.4 -> 1.18.0

Now moving on to testing my use case.

**Comment by kazetsukaimiko** [comment]
So at first I thought I might have a chance at the fluent interfaces handling the "upgrade" from Keyless to Keyed Dao builder::
```
// withPrimaryKey fluent method returns a KeyedDaoBuilder with existing PK validation)
DaoBuilder<ENTITY> entityDaoBuilder = new DaoBuilder<>(tableName, ENTITY::new)
  .withPrimaryKey("id", "ID_SEQUENCE", ENTITY::getId, ENTITY::setId) 
// ...
entityDaoBuilder.buildDao(connection); // Problem: entityDaoBuilder is still declared as DaoBuilder (keyless), so unless we declare as Keyed from the start...
```

So my conclusion here is that one will have to declare, explicitly, a KeylessDaoBuilder if they want to entertain this use case.

**Comment by ojplg** [comment]
Yeah, I thought about your problem for a bit, and then remembered why I wrote the code the way I did.

My prior comment about how to do this was 100% baloney.

The biggest issue is the return type of the withX() methods, which need to be exactly the type of the class, not an interface or abstract class. And since the generic signature of the Indirect variant is completely different ... well, that's why I said the implementation is ugly, but the client interface is easy.

I still think the right thing to do is to have a `KeylessDao` interface that removes anything primary key related and then make `Dao` extend that, so that it remains basically the same thing. But then, yeah, you need a `KeylessDaoBuilder` and sharing code between the various builders is always going to be awkward.

**Comment by kazetsukaimiko** [comment]
It works, now what's left is cleanup, and tests.

```

        KeylessDaoBuilder<MigrationLog> migrationLogDaoBuilder = new KeylessDaoBuilder<>("database.migration_log", MigrationLog::new)
                .withConvertingStringColumn("uuid", MigrationLog::getUuid, MigrationLog::setUuid,
                        new Converter<UUID, String>() {
                            @Override
                            public String from(UUID item) {
                                return item.toString();
                            }
                            @Override
                            public UUID to(String s) {
                                return UUID.fromString(s);
                            }
                        })
                .withLocalDateTimeColumn("time", MigrationLog::getTime, MigrationLog::setTime)
                .withStringColumn("type", MigrationLog::getType, MigrationLog::setType)
                .withStringColumn("message", MigrationLog::getMessage, MigrationLog::setMessage);

        Connection connection = DriverManager.getConnection(jdbcConnection);

        KeylessDao<MigrationLog> migrationLogDao = migrationLogDaoBuilder.buildDao(connection);
```

I think my change to DaoDescriptor is a key architectural decision that needs thinking:
```
    /**
     * The primary key for objects of type <code>ENTITY</code>
     *
     * @return the primary key, if there is one. Else, Optional.empty()
     */
    Optional<PrimaryKey<ENTITY, ENTITYBUILDER>> primaryKey();

```
This required alot of test code changes. The alternative to this is making a KeylessDaoDescriptor class. 90%~ of the code can be shared between keyed and keyless versions of these interfaces by having the Keyed class be a subclass of the Keyless class. 

There are no test failures that I can see from running mvn clean package, but additional coverage is probably needed.

**Comment by ojplg** [comment]
I will take a look at your code.

I think my concern is distinguishing between things that can be joined (have keys) and things that cannot. What's the plan for that?

The reason for a Keyless set of things (builders, daos, descriptors) is to segregate things in the type system so the compiler prevents a join that will not work.

How are you thinking about this?

**Comment by kazetsukaimiko** [comment]
I think the first iteration of Keyless anything shouldn't support joins in either direction. All of that functionality should be moved to the (implicitly) "keyed" classes. If the use case comes up we can address it.

These rows are not logically guaranteed to be unique, thus they're keyless. At the very least,
one-to-(one,many) is not supported. Conceptually its possible we could support many-to-one (in the case that the other table is keyed) or many-to-many (regardless if the other table has keys or not), but the latter sounds like trouble.

Opening the PR for feedback on the specifics.

**Comment by kazetsukaimiko** [comment]
Lets say you're tracking ReadEvents for Lines in a Book (which has a Version). Different Versions of a Book all have the same Book Id, and while ReadEvents have no unique identifier, Lines are canonized across Versions as well. 

ReadEvent: bookId, versionId, lineId, timestamp, // some other identifiers around who

So now you're an analyist interested in how many times a Line in a Book was Read, regardless of Version. In this case, one way or another the bookId is a part of the selection criteria, and is a unique something we're referencing, and could fairly easily be a part of a join.

I'm having trouble thinking of a use case where you'd support a join for a keyless table, but not have the join subject as part of the selection criteria on the keyless table.

**Comment by ojplg** [comment]
I pulled your fork into a branch so I could start playing with it. See here: https://github.com/ojplg/hrorm/tree/kazetsukaimiko-keyless

I created a new `KeylessDaoDescriptor`.

What I am thinking about is that some things are eligible to be joined or to be children of other entities. At the moment, keyless entities are not. So, I want the type system to reflect that they are limited in that way. They can have children, and they can join things to them, but they cannot be children or be joined. And I do not think that having an `Optional<PrimaryKey>` is the right way to express that. That would lead to runtime exceptions, and it's better to have the compiler tell you something structural like that is wrong.

What do you think of this approach? I think it does what you want?

**Comment by kazetsukaimiko** [comment]
"it's better to have the compiler tell you something structural like that is wrong."
I agree, my PR was to capture the intent of my use case and explore how it could be implemented architecturally. Optional was for expediency, KeylessDaoDescriptor is the right way to actually implement this. 

I've merged your branch's changes back into mine and will continue testing.
https://github.com/kazetsukaimiko/hrorm/pull/1

**Comment by kazetsukaimiko** [comment]
Cleaned up KeylessDaoImpl to not have the primaryKey field. 

I think I may be able to implement deleteManyByColumns(ENTITY item, String... columnNames) myself but need a hand, or need to have a closer look at sqlBuilder/sqlRunner/buildFunction to implement updateManyByColumns(ENTITY selectionItem, String[] selectionColumnNames, ENTITY updateItem, String[] updateColumnNames).

The idea behind the update function I'm proposing is that you select by one example "selectionItem" ENTITY with a set of specified selectionColumnNames, and update that selection with another example "updateItem" ENTITY using another column name set/updateColumnNames.

**Comment by ojplg** [comment]
I have done some more work which you should probably pull. I am trying to make a clean division in all the places necessary between the keyless variants and the main, keyed classes and interfaces.

But, I am going to stop since I think we are more likely to be stepping on each other's toes and ending up trying to merge things.

Let's try to focus on one thing at a time: this keyless work is pretty big. Adding the new functions ought to be small and straightforward when this is done.

**Comment by kazetsukaimiko** [comment]
Merging your changes now. I was able to avoid a KeylessSqlBuilder split by adding constructors in  the (Keyless)DaoImpl classes, didn't seem like there was much of a split there, but I see why you'd want to do it that way. 
https://github.com/kazetsukaimiko/hrorm/commit/c301d0f2536550384fd69a35b5ebd182b463affa
I'll defer to your changes over my own, except in one case I think is more semantically elegant (Stream concat vs new List in the SqlRunner class):
https://github.com/kazetsukaimiko/hrorm/commit/ad5a074de8898cb53e77fbf4b833dbcedb889770#diff-ee498a34710db8baa7154b5f579aec5bR36

As for the new functions, I was thinking of a more flexible fluent query mechanism that could be implemented, I'll remove the current functions, open another branch for those along with the new mechanism.

**Comment by kazetsukaimiko** [comment]
What do you think is left to do here? Seems to work okay, I'm running around updating comments right now...
Trying to also think of any edge cases for testing. 

Also, I mentioned in the PR, but I was wondering why Validator isn't being used to find/throw the No PK exception?

**Comment by ojplg** [comment]
I will take a look (probably tomorrow) and let you know what I think.

**Comment by ojplg** [comment]
I pulled this code into the master branch.

I have made more changes from where you left it.

I think the documentation needs a lot of work now. And there are tests to write.

You had two other ideas:
* Select by comparison and range, which you opened a ticket for
* Non-Long primary keys

I would like to do these things one at a time. I think you felt that the select work was more important. Let me know what you think.

Also, should I close this ticket? Or do you still have open questions about this?

**Comment by kazetsukaimiko** [comment]
Thanks, lets close this ticket. Great work all around. 

"I think the documentation needs a lot of work now. And there are tests to write." If you'd like a hand, I would suggest opening another issue on this. If we can enumerate the work, it can be divided up.

I would suggest moving on to comparison/range queries/query enhancements.
