### ISSUE TITLE
Map binary ASN.1 objects such as PKCS certificates

### ISSUE THREAD

**Issue by ajitgeorge** [ojplg/hrorm#16]
Wouldn't it be useful if one could hrorm up certificates into objects in memory?

**Comment by ojplg** [comment]
That's why Hrorm has a Generic Converter<YOURTYPE, DBTYPE> interface. You can persist whatever you like.

See here: https://hrorm.org/javadocs/latest/org/hrorm/Converter.html
And here: https://hrorm.org/javadocs/latest/org/hrorm/DaoBuilder.html#withConvertedGenericColumn-java.lang.String-java.util.function.Function-java.util.function.BiConsumer-org.hrorm.GenericColumn-org.hrorm.Converter-

In the meantime, since I suspect there was some sarcasm involved in this request, I am closing with extreme prejudice.
