### ISSUE TITLE
Boolean failure on MS-SQL, bit type column

### ISSUE THREAD

**Issue by kazetsukaimiko** [ojplg/hrorm#6]
I'm getting into my use case a bit, and ran into an exception.

I noticed booleans are treated like strings internally, booleans are typically represented by numeric types:

```
MySQL  | TINYINT(1)
PostgreSQL  | BOOLEAN
SQL Server 2014 | BIT
Oracle 11g | BOOLEAN
```

I'm getting a stack trace:
```
org.hrorm.HrormException: Unsupported string: 0
org.hrorm.BooleanConverter.to(BooleanConverter.java:31)
org.hrorm.BooleanConverter.to(BooleanConverter.java:11)
org.hrorm.DataColumnFactory$5.fromResultSet(DataColumnFactory.java:152)
org.hrorm.AbstractColumn.populate(AbstractColumn.java:48)
org.hrorm.SqlRunner.populate(SqlRunner.java:192)
org.hrorm.SqlRunner.foldingSelect(SqlRunner.java:110)
org.hrorm.SqlRunner.selectByColumns(SqlRunner.java:64)
org.hrorm.KeylessDaoImpl.selectManyByColumns(KeylessDaoImpl.java:146)
```

I added case statements in BooleanConverter for strings "0" and "1" (in addition to "F" and "T") for the time being to see if that will fix my issue, if so I can issue a PR for that. Don't know if you have any other ideas around how you want to handle these. Perhaps it is safe to continue handling them as strings with enough options.

**Comment by ojplg** [comment]
I think the best thing to do is to create a new column type. Your fix will work for you to read things, but then if you try to write, what do you do? An "F" or a 0?

Everyone has a different idea about how to handle booleans. The DBAs I worked with most recently liked using T and F, so that's what I got used to.

**Comment by kazetsukaimiko** [comment]
Yeah, my use case is read-only. I'll see what the "JDBC way of doing things" is and try to apply it as best I can in my PR.

**Comment by ojplg** [comment]
I pulled your code, since it seemed like the right thing to do.

I just changed the tests to use type "boolean".

Oracle appears to be the outlier here. Boolean is an ANSI SQL type. Maybe Oracle supports it now, but they have not always in the past.

I think perhaps there should be methods like "withBooleanAsStringColumn" and "withBooleanAsIntegerColumn" with appropriate data converters.

Let me know if you want me to cut a release with this fix. I might do it anyway.

**Comment by kazetsukaimiko** [comment]
ANSI SQL Boolean = Oh, even better. I was looking around for some kind of spec to use as a source of truth on the matter but didn't immediately find something. I wrote the code up on a GPD Win 2, with 6 inch ish screen. I was out and about and didn't have alot of time to dig.

For numeric columns I think JDBC will do a decent job of abstracting numeric/boolean conversions for you (0 = false, >0 = true, <0 = ?, probably true), so I question the necessity of a method specifically for that use case.

For Strings, it would be easy enough to add to the DaoBuilder, but I think you should require the implementer to be explicit in specifying what constitutes true or false, and how the ORM layer should attempt to persist.

To test the conversions I was going to create two entities representing the same table, one with native numeric/string fields and the other with boolean conversions, populate the table with random data from both sides, then use the raw entities coming out to compare the behavior of the converting entities. If you'd like I can put another PR in for that.

I think a release would be good. Don't see other work making it in at this point.

**Comment by ojplg** [comment]
I cut release 0.6.1 and updated everything.

It should be easy to add methods to support string backed or integer backed boolean columns, but I have not bothered to actually do so. Pure laziness.

Closing this.
